fuel_name: beechwood
expr_name: 5s10r-01
is_restart: false
ns: 5
nr: 10
n_train: 3
batchsize: 256

lb: 1.e-6
n_epoch: 2500
n_plot: 10
grad_max: 1.e2
maxiters: 50000

lr_max: 1.e-3
lr_min: 1.e-5
lr_decay: 0.2
lr_decay_step: 500
w_decay: 1.e-8
